### ISSUE TITLE
Kääntämättömät rakennukset näkyvät nimellä Restaurant Pier

### ISSUE THREAD

**Issue by ZeroOne3010** [hanskurppa/csfi#2]
Hei! Huikeaa työtä tämän käännöksen kanssa, kiitos tästä! Kiva erityisesti nuoremmalle pelaajalle, joka ei vielä englantia osaa. 😊

Tässä käännöksessä on nyt kuitenkin sellainen ongelma, että kaikki kääntämättömät rakennukset näkyvät nimellä "Restaurant Pier". Huomasin tämän jo kun silmäilin käännöstiedostoa, mutta nyt varmistin asian asentamalla käännöksen ja käynnistämällä pelin.

**Comment by hanskurppa** [comment]
Kiitos ilmoituksesta. Totta, näytti olevan 90+ virheellistä käännöstekstiä. Nyt pitäisi olla korjattu versio tarjolla.

**Comment by ZeroOne3010** [comment]
Kiitos, sehän oli nopea korjaus! Niin nopea, etten ehtinyt laittaa tänne seuraavaa samansuuntaista havaintoa: suuri osa erilaisista ajoneuvoista kulkee nimellä "Bicycle" tai "Light Aircraft ", ja monet eri tiet taas nimellä "Bicycle Path"... :sweat_smile: Lisäksi tuosta kun vähän selaan käännöstiedostoa, niin ilmeisesti "Too many prisoners!" ja "Building is out of use because of flooding!" ovat myös viestejä, joita käytetään liikaa. 

Mutta tosiaan, hieno projekti tämä on edelleen yhtä kaikki! Otatko pull requesteja tähän vastaan jos oikein innostun ja löydän aikaa? Chirppien mainitset olevan "out of scope", mutta olisko ne "in scope" jos joku muu tekisi niitä?

**Comment by hanskurppa** [comment]
Onkohan tuo sekoillut siinä vaiheessa, kun käytin kerran testinä Poeditin läpi. Normaalisti tullut tehtyä vaan suoraan tekstieditorissa po-tiedostoon.

Kävin nyt kaikki tekstit läpi ja poistin virheelliset `msgstr "englanninkielinen fraasi"` eli tilalle `msgstr ""`. Näitä saa suht helposti selattua esim. VSCodessa kun hakee regex `msgstr ".+"`, joka maalaa kaikki msgstr-rivit joissa on sisältöä. Voi olla, että joku jäi vielä bongaamatta.

En ole kääntänyt aktiivisesti pariin vuoteen, lähinnä tullut päiviteltyä locale-tiedostoa, kun tulee uusia Cities versioita. 100% itse kääntämääni kaikki tähän mennessä, mutta otan mielelläni vastaan pull requesteja jos muillakin on innostusta kääntää tai korjata.

Chirpit on olleet out of scope, koska niitä on niin valtavasti. Ehkä jos tuohon toimisi joku fiksu ML/AI-käännös. Voishan se olla tietysti oma humoristinen vivahteensa kun chirpit rikkinäistä konekäännös-suomikieltä. B)

**Comment by ZeroOne3010** [comment]
Minua kyllä kiehtoo ajatus siitä, että noita chirppejä voi myös lokalisoida eikä pelkästään mekaanisesti kääntää. Tuossa olisi sata ensimmäistä käännettyinä, mitä pidät: https://github.com/hanskurppa/csfi/commit/96aa9d9649785046782f31937c3b46e00d441a9e ? :)

**Comment by hanskurppa** [comment]
Loistavaa. Laitetaan vaan mukaan. Vielä kun osaisin käyttää GitHubia, että nuo saa kyytiin... :D

**Comment by ZeroOne3010** [comment]
Teen noista pull requestin kun ehdin, sitten se hoituu nappia painamalla. 😊

**Comment by ZeroOne3010** [comment]
Ja noin: #3

**Comment by hanskurppa** [comment]
Kiitos. Päivitetty.

**Comment by ZeroOne3010** [comment]
Alkuperäinen ongelmakin tuli hoidettua, kiitos siitä. Suljen tämän tiketin. :) Tein myös äsken uuden pull requestin, jossa oli taas uusia käännöksiä.
