### ISSUE TITLE
Financial Districts + .po <-> .locale?

### ISSUE THREAD

**Issue by ZeroOne3010** [hanskurppa/csfi#6]
Pari juttua: 

1. Käännöstiedostossa ei näytä olevan Financial Districts -lisäosan tekstejä. Olisivatko ne tässä, saisitko ne mukaan tästä en-localesta:
[en.zip](https://github.com/hanskurppa/csfi/files/10419974/en.zip)?
2. Jaksaisitko raapustaa readme-tiedostoon ohjeet, miten .po-tiedostoja muutetaan .locale-tiedostoiksi ja toisin päin? :)

**Comment by hanskurppa** [comment]
mergepo.ps1 tiedoston alussa on ohjetta.

**Comment by hanskurppa** [comment]
Käännöstyökalun latauslinkki ei ilmeisesti enää toimikaan Paradoxin foorumissa. Lisäsin sen nyt tähän repoon. Siinä ei tullut koskaan mitään lisenssiä tai muutakaan mukana, joten saanee nyt olla tuossa jaossa (ehkä, en tiedä, poistetaan jos jotain häiritsee).

**Comment by hanskurppa** [comment]
Ei toimikaan tuo oma PowerShell-räpellykseni nyt niinkuin pitäisi. Generoi turhan isoa outputia. No eniveis, tarkoitus sillä on ollut vain jollain logiikalla yhdistellä uudesta en.po tiedostosta uudet kääntämättömät tekstit siihen olemassa olevaan fi.po tiedostoon, kun ei tuo käännöstyökalu sitä osaa. Jotain parempaa koodia tilalle tai onnistuisko ihan vaan jollain diff-työkalullakin.

**Comment by hanskurppa** [comment]
Niin ja voin kyllä antaa tähän repoon Collaborator-oikeudet, tai miten täällä GitHubissa kannattaa yhteisiä repoja tehdäkään. Jos siis onnistut itsekin generoimaan tuon lopullisen fi.locale, niin ei tarvitse odotella "julkaisua" minun kauttani.

**Comment by ZeroOne3010** [comment]
Okei, kiitos tiedosta! Näköjään tiedostojen konvertointi onnistuu. Voisin itsekin katsoa, josko saisin noita yhdisteltyä jotenkin. :thinking:

**Comment by ZeroOne3010** [comment]
No niin, tein tällaisen pienen sovelman noiden tiedostojen yhdistämiseen, tuntuu toimivan: https://github.com/ZeroOne3010/pomerger Teen vaikka myöhemmin vielä PR:n, jossa on Financial Districtsin tekstit sekä lisää käännöksiä.

**Comment by hanskurppa** [comment]
Saiskohan tuon tehtyä tälläkin: https://www.gnu.org/software/gettext/manual/html_node/msgcat-Invocation.html

**Comment by ZeroOne3010** [comment]
Todennäköisesti saisi, ja vähän yritinkin, mutta luovutin kun en viidessä minuutissa keksinyt oikeita asetuksia... 😅

**Comment by ZeroOne3010** [comment]
PR: #8
